Full task 2 pull request
2immons/EPAM pull request #4
Opened 2022-01-26 16:08 UTC by 2immons

2022-01-27 09:37 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figure.cs
> +        public int side2 { get; set; }
не у всех фигур есть внутренний и внешний радиусы и 2 стороны

2022-01-27 09:42 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figure.cs
> +    public class Figure
этот класс должен быть абстрактным

2022-01-27 09:42 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figure.cs
> +            this.side2 = side2;
что может означать side2 у линии?

2022-01-27 09:44 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figure.cs
> +    public class Сircumference : Circle
было бы логичнее наследовать круг от окружности, а не наоборот

2022-01-27 09:50 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figure.cs
> +        public double CircleSquare()
поиск площади и периметра фигуры лучше вынести в класс figure и переопределять в классах наследниках

2022-01-27 09:54 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Program.cs
> +                index = PrintWindow(name);
думаю, индекс лучше спрашивать в начале цикла, а не в конце

2022-01-27 09:55 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Program.cs
> +                return;
у пользователя есть шанс выйти только сразу после запуска?

2022-01-27 09:58 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Program.cs
> +                        Console.WriteLine("{0} : Center: {1}, {2} ; OutR = {3}", typeof(Circle), item.X, item.Y, item.outRadius);
площадь фигуры никак не отображается?

2022-01-27 09:59 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Program.cs
> +                        Console.WriteLine("{0} : Center: {1}, {2} ; OutR = {3}", typeof(Circle), item.X, item.Y, item.outRadius);
если бы у класса Figure был метод для получения информации о фигуре, не пришлось бы городить кучу if else

2022-01-27 10:14 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        public static int Length(StringAsArray str) // поиск длинны массива символов
лучше делать такие методы не статическими
(вызывать не StringAsArray.Length(str), а str.Length)

2022-01-27 10:14 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        public static string ToString(StringAsArray str) // конвертация из массива символов в строку
лучше не статический метод, а оверрайд ту стринга класса object

2022-01-27 10:15 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +            return str.StringArray.ToString();
это не работает как создание строки из массива символов

2022-01-27 10:18 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +                    resultStr += str.StringArray[i];
во первых, тут не стоило использовать стринг по заданию, во вторых, если и использовать, то тут нужен StringBuilder, но лучше реализовать свой функционал

2022-01-27 10:20 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +            string vs = new string(temp);
можно было использовать конструктор StringAsArray, который принимает массив символов (если нет, добавить)

2022-01-27 10:22 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        public static bool operator <(StringAsArray str1, StringAsArray str2) // перегрузка оператора <
для строк не очевидно что может означать операторы < и >, а имплементировать IComparable и IEquatable как у обычной строки стоило бы

2022-01-27 10:23 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        public char[] StringArray { get; set; }
это свойство никак не связанно с приватным полем arr

2022-01-27 10:24 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        public static int IndexOf(StringAsArray str, string sStr) => str.ToString().IndexOf(sStr);
почему метод статический?

2022-01-27 10:27 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +{
в пул реквесте может быть и удобнее проверять много классов, когда они рядом, но лучше все таки их разбивать на отдельные файлы

2022-01-27 10:29 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +    abstract class GameElements
названия классов лучше делать словами в единственном числе

2022-01-27 10:34 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +    abstract class Object : GameElements { }
какой-то пустоватый класс, судя по коду дальше, можно было бы добавить что-нибудь вроде CollideWith(Character)
и лучше не называть классы похоже на системные классы (например, назвать этот класс StaticObject или GameObject)

2022-01-27 10:36 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +            this.Y = 15;
а не лучше ли передавать в конструктор место, где игрок должен появляться?

2022-01-27 10:37 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +        public static int[] KeyPressCheck()
должны ли этот метод вызывать вне этого класса?

2022-01-27 10:40 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +            this.Y += coordinates[1];
если сделать метод KeyPressCheck приватным, можно передавать значения с помощью кортежа (int,. int), а не массива из 2 интов (но лучше все таки создать структуру вектор для этого)

2022-01-27 10:40 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +            if (this.X > 1 && this.Y > 1 && this.X < 28 && this.Y < 28)
думаю, ограничения размера поля должны быть не захардкожены

2022-01-27 10:42 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/GameElements.cs
> +            if (this.X > 1 && this.Y > 1 && this.X < 28 && this.Y < 28)
тут то же, что и у зомби, не стоит хардкодить числа ограничений
к тому же, не стоит оставлять в коде магические числа, которые не известно, к чему привязаны и что означают

2022-01-27 10:42 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/Program.cs
> +    // Цель игры - собрать бонусы ($ на карте), постоянно пополняя свое HP (+ на карте)
так HP или адреналин?

2022-01-27 10:49 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/Program.cs
> +        private const int mapWidth = 30;
должны ли быть огнаничения карты приватными, если они константные?

2022-01-27 10:51 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/Program.cs
> +                return false;
какой-то хардкорный способ ограничить передвижение игрока

2022-01-27 10:53 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/Program.cs
> +        static bool CheckForLoseOrVictory(List<Character> characters, List<Object> objects, Player player)
почему листы объектов передаются как параметры, а не хранятся в классе?

2022-01-27 11:04 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/Program.cs
> +        static bool CheckForLoseOrVictory(List<Character> characters, List<Object> objects, Player player)
судя по названию, сначала подумал, что метод возвращает true если игрок выйграл и false если проиграл, но по факту метод проверяет, должна ли игра продолжаться

2022-01-27 11:06 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/Program.cs
> +                    if (itemType.Equals(typeof(Obstacle)))
почему не if (item is Obstacle)?
думаю, если бы у Obstacle были классы-наследники, у них бы была похожая логика

2022-01-27 11:08 UTC, NulleanAndRain commented on Task2/Task 2.2/EPAM Task 2.2.1/Program.cs
> +                new Wolf(rnd.Next(1, 28), rnd.Next(1, 28))
что за магические числа?

2022-01-27 11:09 UTC, NulleanAndRain requested changes
Поправь класс строки и обрати внимание на остальные замечания по коду

2022-01-27 13:47 UTC, 2immons commented
> Поправь класс строки и обрати внимание на остальные замечания по коду

**исправил 2.1.2 про фигуры:**
разбил классы по файлам;
поправил логичность наследования (подправил названия переменных; в базовом классе оставил только то, что используется везде в наследниках);
добавил собственные функции вывода для каждого класса;
добавил вывод недостающих характеристик объекта (раньше не выводилась площадь и др.);
поправил смену пользователя (теперь в любой точки программы можно сменить пользователя);
перенес спрашивание индекса в начало цикла;
+мелкие доработки.

2022-01-28 17:31 UTC, 2immons commented
> Поправь класс строки и обрати внимание на остальные замечания по коду

**исправил 2.2.1 (игра):**
разбил классы по файлам - вынес "поле" в отдельный класс;
исправил названия методов, переменных;
убрал магические числа, заменил все "нехардкорными" переменными;
подправил уровни доступа к некоторым методам;
теперь координаты Player задаются не по стандарту - их нужно передать в конструкторе;
+мелкие доработки.

2022-01-29 13:06 UTC, 2immons commented
> Поправь класс строки и обрати внимание на остальные замечания по коду
**исправил 2.1.1 (строки):**
подправил класс StringAsArray;
реализовал функции через свой функционал, а не через string'овский;
исправил поля, спецификаторы, методы;
+мелкие доработки.

2022-02-11 06:54 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figures/Rectangle.cs
> +        public Rectangle(int x, int y, int side1, int side2) : base(x, y, side1)
по названиям переменных не очевидно, что это координаты центра

2022-02-11 06:54 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figures/Rectangle.cs
> +            this.Side1 = side1;
все, кроме Side2 задается в конструкторе Square, зачем дублировать здесь?

2022-02-11 06:56 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figures/Ring.cs
> +            this.OuterRadius = outerRadius;
опять же, лишнее повторение кода

2022-02-11 06:58 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figures/Ring.cs
> +        public override double GetSquare() => Math.PI * OuterRadius * OuterRadius;
у кольца в площадь не включается площадь внутреннего круга (формула будет Math.PI * (OuterRadius * OuterRadius - InnerRadius * InnerRadius)

2022-02-11 07:01 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figures/Triangle.cs
> +            return Math.Sqrt(perimetr * perimetr - Side1 * perimetr - Side2 * perimetr - Side3);
потерял скобки в формуле, к тому же в ней использовался полупериметр, а не периметр

2022-02-11 07:02 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figures/Triangle.cs
> +            this.Side3 = side3;
а если среди 3х линий не будет ни одной пары совпадающих точек?

2022-02-11 07:03 UTC, NulleanAndRain commented on Task2/Task 2.1/EPAM 2.1.2/Figures/Triangle.cs
> +            this.Side3 = side3;
лучше все-таки задавать треугольник 3 точками, а не 3 линиями

2022-02-11 07:10 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        private char[] StringArray = new char[30];
приватные переменные принято называть, начиная название с нижнего подчеркеркивания (и строчной буквы после него)

2022-02-11 07:11 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        private char[] StringArray = new char[30];
зачем сразу записывать в это поле массив на 30 элементов, если потом он будет перезаписан в конструкторе?

2022-02-11 07:14 UTC, NulleanAndRain commented on Task2/Task 2.1/StringAsArrayLibrary/StringAsArray.cs
> +        public static string ToString(StringAsArray str)
зачем нужен сатический ToString, который перевызывает ToString у объекта?

2022-02-11 07:20 UTC, NulleanAndRain approved these changes
в целом ок, но стоит почитать про стиль кода
https://docs.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/coding-conventions

2022-02-11 15:05 UTC, merged